name: Waka Readme

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN   }}
          SHOW_LANGUAGE : "True"
          COMMIT_BY_ME : "True"
          SHOW_EDITORS : "True"
          SHOW_OS : "True"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_LOC_CHART : "False"
